export const DISPLAY_ALERT = "DISPLAY_ALERT";
export const CLEAR_ALERT = "CLEAR_ALERT";

export const SETUP_USER_BEGIN = "SETUP_USER_BEGIN";
export const SETUP_USER_SUCCESS = "SETUP_USER_SUCCESS";
export const SETUP_USER_ERROR = "SETUP_USER_ERROR";

export const LOGOUT_USER = "LOGOUT_USER";

export const TOGGLE_BIG_SIDEBAR = "TOGGLE_BIG_SIDEBAR";
export const TOGGLE_SMALL_SIDEBAR = "TOGGLE_SMALL_SIDEBAR";
