export const surveyJson = {
    "title": "Demo Assessment Form",
    "logoPosition": "right",
    "focusFirstQuestionAutomatic": false,
    "pages": [
     {
      "name": "page1",
      "elements": [
       {
        "type": "panel",
        "name": "panel1",
        "elements": [
         {
          "type": "dropdown",
          "name": "productLine",
          "maxWidth": "40%",
          "title": "Product Line",
          "choices": [
            "Screw",
            "Nail",
            "Anchor"
          ]
         },
         {
          "type": "dropdown",
          "name": "company",
          "maxWidth": "40%",
          "startWithNewLine": false,
          "title": "Company",
          "choices": [
            "Simpson Strong-Tie",
            "Hilti",
            "DeWalt"
          ]
         },
         {
          "type": "text",
          "name": "modelName",
          "maxWidth": "40%",
          "startWithNewLine": false,
          "title": "Model Name",
         }
        ],
        "choices": [
         1,
         2,
         3,
         4,
         5
        ],
        "allowAddRows": false,
        "allowRemoveRows": false,
        "rowCount": 1
       },
       {
        "type": "tagbox",
        "name": "application",
        "title": "Application",
        "choices": [
         "Beam Reinforcement",
         "Coastal / Salt Air",
         "Cold-Formed Steel",
         "Cooling Towers",
         "Corrosive Environments",
         "Crating",
         "DIY / Home Projects",
         "Deck Framing",
         "Decking - Composite",
         "Decking - Metal",
         "Decking - Wood",
         "Deflection",
         "Dock and Boardwalk",
         "Drywall",
         "Engineered Wood",
         "Engineered Wood: Multi-Ply Fastening",
         "Factory-Built/Modular Construction",
         "Fastening Butt Joists",
         "Fastening Fiber-Cement Siding",
         "Fastening Fiberglass-Backed Sheathing",
         "Fastening Fire-Retardant Treated Lumber",
         "Fastening Floor-to-Floor",
         "Fastening Siding to Steel",
         "Fastening Siding to Wood",
         "Fastening Simpson Strong-Tie Connectors",
         "Fastening Stud-to-Plate",
         "Fastening Subfloor to Wood",
         "Fastening Support Beams",
         "Fastening Truss / Rafter-to-Plate",
         "Fastening Wall-to-Wall",
         "Fastening Wood Siding",
         "Fastening Wood to Steel: Sheathing",
         "Fastening Wood-to-Aluminum",
         "Fastening Wood-to-Steel",
         "Fastening Wood-to-Steel: Nailers and Ledgers",
         "Fastening Wood-to-Wood",
         "Fastening for Cold-Formed Steel",
         "Fencing",
         "Finishing, Millwork and Trim",
         "Flood-Resistant Construction",
         "Framing: Cold-Formed Steel",
         "Framing: Wood",
         "Furniture",
         "General Framing",
         "General Interior",
         "Heavy Timber",
         "Log-Home Construction",
         "Marine",
         "Mass Timber / Cross-Laminated Timber",
         "Metal Roofing and Siding: Exopsed Fastener",
         "Metal Roofing: Standing Seam",
         "Miscellaneous",
         "PVC Trim and Fascia",
         "Pier Restoration",
         "Roofing",
         "Roofing: Tile and Slate",
         "Sheathing",
         "Specialty",
         "Steel Decking and Stitching",
         "Steel-to-Wood / Engineered Wood",
         "Storm Panels",
         "Structural Composite Lumber",
         "Tongue-and-Groove Decking / Flooring",
         "Truck Beds / Trailer Flooring",
         "Truss-Ply Fastening",
         "Underlayment / Backerboard",
         "Wire Lath",
         "Wood / Residential Construction"
        ]
       },
       {
        "type": "tagbox",
        "name": "material-coating",
        "title": "Material/Coating",
        "choices": [
         "Yellow-Zinc Plating",
         "Clear Zinc Plating",
         "Electrocoating (E-Coat™)",
         "Gray Phosphate Coating",
         "Black Phosphate Coating",
         "Class 1 Zinc Plating",
         "Coated Zinc",
         "Quik Guard® Coating",
         "Double-Barrier Coating",
         "Class D Hot-Dip Galvanized, ASTM A153",
         "N2000® Mechanically Galvanized",
         "Class 55 Mechanically Galvanized, ASTM B695",
         "C-3 Mechanically Galvanized",
         "Class C, Hot-Dip Galvanized, ASTM A153",
         "Blue-Zinc Plating",
         "Double-Barrier Black Coating",
         "Wax Fuchs-Lubritech Gleitmo 615",
         "Wax ADREM P/N 615-F",
         "PPG Powercron XP Cathodic Electrocoat",
         "PPG Powercron XL Black Cathodic Electrocoat",
         "Magni 599 W57 Grey",
         "HWR-F Water Based Rust Inhibitor",
         "MR-27F White Ruspert",
         "Magni 599 W117 Silver",
         "Magni 599 W56 Tan",
         "Ruspert Pantone 179 Orange Dip Spin Coating",
         "Wax Atotech #9 Friction Modifier",
         "Carbon Steel",
         "Type 304 Stainless Steel",
         "Type 305 Stainless Steel",
         "Type 316 Stainless Steel",
         "Type 316L Stainless Steel",
         "Type 410 Stainless Steel"
        ]
       },
       {
        "type": "tagbox",
        "name": "head-type",
        "title": "Head Type",
        "choices": [
         "Box-Shaped Cutter Head",
         "Bugle Head",
         "Cap Head",
         "Combination",
         "Compact Head",
         "Flat Head",
         "Flat Head with Nibs",
         "Flat Pan Head",
         "Hex Head",
         "Hex Washer Head",
         "Large Hex Washer Head",
         "Low Profile Head",
         "Modified Truss Head",
         "Pan Head",
         "Pancake Head",
         "Ribbed Flat Head",
         "Ribbed Wafer Head",
         "Rimmed Flat Head with Nibs",
         "Trim Head",
         "Trim Head with Nibs",
         "Truss Head",
         "Ultra-Low Profile Pancake Head",
         "Wafer Head",
         "Washer Head"
        ]
       },
       {
        "type": "tagbox",
        "name": "drive-type",
        "title": "Drive Type",
        "choices": [
         "#1 Square",
         "#2 Phillips",
         "#2 Square",
         "#2 Square, Undersized",
         "#3 Phillips",
         "#3 Phillips or 7/16 in. Hex",
         "#3 Square",
         "#3 Square, Undersized",
         "1/4 in. Hex",
         "1/2 in. Hex",
         "3/8 in. Hex",
         "5/16 in. Hex",
         "T10 6-Lobe",
         "T15 6-Lobe",
         "T20 6-Lobe",
         "T25 6-Lobe",
         "T27 6-Lobe",
         "T30 6-Lobe",
         "T40 6-Lobe",
         "T40 6-Lobe or Hex-Head",
         "T50 6-Lobe"
        ]
       },
       {
        "type": "tagbox",
        "name": "thread-type",
        "title": "Thread Type",
        "choices": [
         "Box Threads",
         "Coarse Threads",
         "Fine Threads",
         "High/Low Serrated Threads",
         "High/Low Threads",
         "Machine Threads",
         "Serrated Threads",
         "Metal Tapping Threads",
         "Tri-Lobe Threads",
         "Triple-Thread Design",
         "Twin Threads",
         "Variable Threads Design",
         "Reverse Threads",
         "One Flute",
         "Buttress Threads"
        ]
       },
       {
        "type": "tagbox",
        "name": "shank-type",
        "title": "Shank Type",
        "choices": [
         "Knurls",
         "Shank Slot",
         "Partially Threaded Shank",
         "Fully Threaded Shank",
         "Annular-Ring Shank",
         "Screw Shank",
         "Smooth Sank",
         "Spiral/Ring Shank"
        ]
       },
       {
        "type": "tagbox",
        "name": "point-type",
        "title": "Point Type",
        "choices": [
         "Drill Point",
         "Drill Point with Wings",
         "Fast-Start point with Helical Ridge",
         "High-Low Threaded Tip",
         "Paddle Point",
         "Pilot Point",
         "SawTooth® Point",
         "SawTooth® with Type-17 Point",
         "Sharp Point",
         "Type C",
         "Type-17 Point",
         "Type-A Point",
         "Half-Cut Tip",
         "High-Low Threaded Tip with Type-17 Point",
         "Chisel Point",
         "Diamond Point"
        ]
       }
      ],
      "title": "General Info"
     }
    ],
    "showQuestionNumbers": "off",
    "questionErrorLocation": "bottom",
    "showProgressBar": "top",
    "progressBarType": "buttons",
    "completeText": "Submit",
    "showPreviewBeforeComplete": "showAllQuestions",
    "widthMode": "static",
    "width": "1200px"
   }